repositories:
  remote:
   - https://repo.maven.apache.org/maven2
   - https://stocksoftware.artifactoryonline.com/stocksoftware/public
   - https://stocksoftware.artifactoryonline.com/stocksoftware/oss

artifacts:
  javaee_api: javax:javaee-api:jar:7.0

  jsr305: org.realityforge.javax.annotation:javax.annotation:jar:1.0.0
