repositories:
  remote:
   - http://repo1.maven.org/maven2
   - https://stocksoftware.artifactoryonline.com/stocksoftware/public
   - https://stocksoftware.artifactoryonline.com/stocksoftware/oss

artifacts:
  javaee_api: javax:javaee-api:jar:7.0

  jsr305: com.google.code.findbugs:jsr305:jar:3.0.0
